    - name: 'IPCam'
      path: './plugins/siriproxy-ipcam'
      camurls: { 'garage': 'http://192.168.69.81/cgi/jpg/image.cgi', 
                 'porch': 'http://192.168.69.82/cgi/jpg/image.cgi', 
                 'attic': 'http://192.168.69.83/cgi/jpg/image.cgi', 
                 'living room': 'http://192.168.69.85/Jpeg/CamImg.jpg' } #URLs of IP camera image.
      camid: 'username'
      campw: 'password'
      webip: 'http://192.168.69.95' #IP address of web server to cache camera images
